version: "3.9"
services:
  postgres:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_DB: "devdb"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"