version: "3.9"
services:
  postgres:
    image: postgres:14.3-alpine
    env_file:
      - ./db.env
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: payment_api
    env_file:
      - ./app.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  rapidoc:
    image: mrin9/rapidoc:v9.2.0
    container_name: rapidoc
    volumes:
      - ./swagger/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    depends_on: 
      - backend
    environment:
      - SPEC_URL=openapi.yaml
      - RAPIDOC_OPTIONS=render-style='view'
    ports:
      - 8081:80


volumes:
  db:
    driver: local