// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package repository

import (
	"context"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	DiscardPayment(ctx context.Context, id int64) (int64, error)
	GetPaymentStatusByID(ctx context.Context, id int64) (ValidStatus, error)
	ListUserPaymentsByEmail(ctx context.Context, arg ListUserPaymentsByEmailParams) ([]Payment, error)
	ListUserPaymentsByID(ctx context.Context, arg ListUserPaymentsByIDParams) ([]Payment, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
